### ISSUE TITLE
Allow existing directories

### ISSUE THREAD

**Issue by SomeAnotherDude** [website-scraper/node-website-scraper#256]
I tried to set `directory` as `'./'` and got an error
`Error: Directory /home/user/workspace/site/learnopengl.com/test/site exists`
   `    at new ResourceSaver (/home/user/node_modules/website-scraper/lib/resource-saver/index.js:21:10)`
`    at new Scraper (/home/user/node_modules/website-scraper/lib/scraper.js:41:108)`
`    at Promise.try (/home/user/node_modules/website-scraper/index.js:8:10)`
`    at tryCatcher (/home/user/node_modules/bluebird/js/release/util.js:16:23)`
`    at Function.Promise.attempt.Promise.try (/home/user/node_modules/bluebird/js/release/method.js:39:29)`
`    at module.exports (/home/user/node_modules/website-scraper/index.js:7:20)`
`    at Object.<anonymous> (/home/user/workspace/site/learnopengl.com/test/downloader.js:7:1)`
`    at Module._compile (module.js:570:32)`
`    at Object.Module._extensions..js (module.js:579:10)`
`    at Module.load (module.js:487:32)`
`    at tryModuleLoad (module.js:446:12)`
`    at Function.Module._load (module.js:438:3)`
`    at Module.runMain (module.js:604:10)`
`    at run (bootstrap_node.js:383:7)`
`    at startup (bootstrap_node.js:149:9)`
`    at bootstrap_node.js:496:3`

Yes, current directory does exists (thanks, Captain Obvious).

Sometimes use existing directories is useful (for example I want to update previously scraped site).
What do you think about allowing existing directories (probably by adding optional flags)?

**Comment by s0ph1e** [comment]
Hi @SomeAnotherDude 

You can customize resource saving to FS by using [resourceSaver](https://github.com/website-scraper/node-website-scraper#resourcesaver) opition. Original resourceSaver you can find in [lib/resource-saver/index.js](https://github.com/website-scraper/node-website-scraper/blob/501af90c995508fbfbd623f63d391b0ccf2744a8/lib/resource-saver/index.js), and just remove check for existing directory.

I'm not going to add this to main module because the idea is to download website to **new** directory. 
Saving to existing directory is tricky:
* different people may expect different behavior from this feature 
* need to implement a lot of logic for resolving conflicts between generated filenames and existing files, handle corner cases like: different access rights to files and directories, symlinks, etc.

**Comment by caidahui** [comment]
test
