### ISSUE TITLE
html file is different than the expected output- this affects the JavaScript files scraped

### ISSUE THREAD

**Issue by AshDee** [website-scraper/node-website-scraper#339]
Hi Team,
I was trying to scrape https://google.com with basic options in website-scraper using puppeteer.

I noticed that the HTML downloaded by website-scraper was different from that displayed in the DevTools and _page.content_.

This affects the files that are downloaded because, in the actual HTML of google.com, there are 5-6 scripts. Since the HTML is changed I don't see any files getting downloaded.

Code Used in website-scraper
let filePath2 = path.resolve(`./Responses/${url.hostname}`);
            const options = {
                urls: 'https://' + x[j][1],
                directory: filePath2,
                sources: [
                    { selector: 'script', attr: 'src' },
                    { selector: 'img', attr: 'src' },
                    { selector: 'link[rel="stylesheet"]', attr: 'href' },
                ],
                subdirectories: [
                    { directory: 'js', extensions: ['.js'] },
                    { directory: 'img', extensions: ['.jpg', '.png', '.svg'] },
                    { directory: 'css', extensions: ['.css'] },
                    { directory:'html', extensions:['.html']}
                    //{ directory: 'fonts', extensions: ['.woff', '.ttf'] }
                ],
                ignoreErrors: true,
                recursive: true,
                maxDepth: 1,
                maxRecursiveDepth:1
            }
            scrape(options).then(function (result) {
                // Outputs HTML 
                //console.log(result);
                console.log("Content succesfully downloaded");
            }).catch(function (err) {
                console.log(err);
            });

There is a different code in the background which gets the domains from a csv file- that's why url has x[j][1].

I have not tried the website-scraper-puppeteer yet.

**Comment by AshDee** [comment]
I tried puppeteer plugin and works as intended but with the headless set as false.  It would be good to check why the HTML gets changed when the puppeteer plugin is not used.

**Comment by s0ph1e** [comment]
Hi @AshDee 

Sorry for late response.

website-scraper without puppeteer plugin and website-scraper with puppeteer plugin return different html, that's expected behavior. 
It happens because website markup is dynamic (rendered by scripts), by default website-scraper does not execute javascript, website-scraper-puppeteer executes javascript and returns result html.

In chrome DevTools->Elements you can see html markup after all scripts executed (and puppeteer plugin will return this html). But if you open `view-source:https://www.google.com/` in searchbar in chrome - you will see original html, returned by server (website-scraper by default returns it)

Hope it helps

**Comment by AshDee** [comment]
Thanks a lot..this makes sense :-) @s0ph1e
