### ISSUE TITLE
single vs double quotes: keep original

### ISSUE THREAD

**Issue by fancydev18** [website-scraper/node-website-scraper#355]
### Configuration
**version:** [result of `npm ls website-scraper --depth 0` command]
website-scraper@4.0.1

**options:** [provide your full options object]
```js

const options = {
        urls: ['https://htmlstream.com/preview/front-v2.7.0/html/pages/pricing.html'],
        directory: 'scrap-1/',
        subdirectories: [
            { directory: 'img', extensions: ['.jpg', '.jpeg', '.png', '.svg', '.gif'] },
            { directory: 'js', extensions: ['.js'] },
            { directory: 'css', extensions: ['.css'] }
        ]
    }

```

### Description

[Description of the issue]

Some HTML attributes have single quotes in the original page, eg:

```
<div class="js-slick-carousel u-slick u-slick--gutters-2 z-index-2"
                 data-slides-show="4"
                 data-adaptive-height="true"
                 data-slides-scroll="1"
                 data-pagi-classes="d-lg-none text-center u-slick__pagination mt-7 mb-0"
                 data-responsive='[{
                   "breakpoint": 1200,
                   "settings": {
                     "slidesToShow": 3
                   }
                 }, ...]'>
```

When saving pages, scraper changes that to double quotes, which breaks the JSON:

```

<div class="js-slick-carousel u-slick u-slick--gutters-2 z-index-2" data-slides-show="4" data-adaptive-height="true" data-slides-scroll="1" data-pagi-classes="d-lg-none text-center u-slick__pagination mt-7 mb-0" data-responsive="[{
                   "breakpoint": 1200,
                   "settings": {
                     "slidesToShow": 3
                   }
                 }, ...
```

**Expected behavior:** [What you expect to happen]

Preserve original quoting style. They know why they chose it.

**Actual behavior:** [What actually happens]

Single quotes are changed to double quotes

**Comment by s0ph1e** [comment]
Hey @fancydev18 

Thanks for reporting issue

`website-scraper` uses `cheerio` to manipulate DOM elements, issue https://github.com/cheeriojs/cheerio/issues/1006 causes this behavior

**Comment by pavelloz** [comment]
I dont know how much manipulation there is going on, but recently i found out that jsdom is extremely good at that.

I was updating only attributes (form, src, href etc.), but maybe this issue doesnt exist there.

**Comment by s0ph1e** [comment]
Hi @pavelloz 
Thank you for suggestion. 

I'm not sure that it's possible to implement similar functionality with jsdom instead of cheerio. 

We're using cheerio because it has flexible selectors and we can easily configure them in config.
For example: https://github.com/website-scraper/node-website-scraper/blob/9c9985b51339aa03cd536b42fdaaeb8ed47015b0/lib/config/defaults.js#L5-L35
I didn't find a way how to do the same with jsdom. Will take closer look

**Comment by pavelloz** [comment]
Hmm. JSDom is actually parsing html, creating virtual dom and you can operate on it like you do in the browser. 

Example:

```js
module.exports = (document) => {
  const css = document.querySelectorAll('link[rel="stylesheet"]');

  css.forEach((el) => {
    if (!isEligible(el.href)) return;

    el.href = assetify(el.href);
  });
};
```

Where document is a html string (ie. response body) parsed by jsdom. 

More context:
https://github.com/mdyd-dev/posify/blob/master/src/lib/replace-urls/index.js

**Comment by pavelloz** [comment]
I found out how to keep original quotes in cheerio: 

```
  const $ = cheerio.load(fileContent, { decodeEntities: false });
```

PS.
Nevermind about jsdom. I just had to switch to cheerio in my project because it was so slow at large sites.

```
cheerio
    posify urls  7.52s user 0.67s system 150% cpu 5.431 total 
```

```
jsdom
    posify urls  55.13s user 1.97s system 129% cpu 44.181 total
```

~9x faster just by switching jsdom to cheerio.

**Comment by aivus** [comment]
Hi @pavelloz 

`decodeEntities: false` is already used by the package:
https://github.com/website-scraper/node-website-scraper/blob/6988b86b42c441a9348cc0dc21e523c1aa9809b8/lib/resource-handler/html/index.js#L82-L87

**Comment by swissspidy** [comment]
What's the current state of this issue? Is this perhaps going to be resolved in v5? If not, how can one help to fix this in v4?

**Comment by s0ph1e** [comment]
Hey @swissspidy 👋 

Currently cheerio update is not planned for v5.

I was waiting for cheerio version 1 (not a release candidate) to be released, but looks like it will not happen soon. 

There were some attempts to update cheerio to latest version (e.g. https://github.com/website-scraper/node-website-scraper/pull/461), but looks like it's not so easy because of breaking changes - some functionality stops working and test fail after the update. 

Everyone is welcome to contribute - feel free to update cheerio and make tests pass again. I will be happy to help with code reviews / suggestions. Otherwise I will try to do it by myself when I have time

**Comment by s0ph1e** [comment]
Now I'm trying to update cheerio again in https://github.com/website-scraper/node-website-scraper/pull/467
So far upgrade looks fine, hopefully it can fix this bug

**Comment by s0ph1e** [comment]
Issue with single and double quotes will be fixed in next release v5. I hope to publish it next week
