### ISSUE TITLE
amd-resources support

### ISSUE THREAD

**Issue by iham** [website-scraper/node-website-scraper#359]
would be nice.

i can't see any resources included by require.js inside any js file.

would that be a new feature or is it already there and i don't see it?

**Comment by s0ph1e** [comment]
Hi @iham 👋

It does not download amd files because [by default scraper download only static websites, it does not execute javascript](https://github.com/website-scraper/node-website-scraper/blob/master/docs/FAQ.md#q-why-website-with-javascript-is-not-downloaded-correcly). I can suggest website-scraper-puppeteer or website-scraper-phantom plugins - they will save page with scripts correctly but probably will not download require.js files. 

Hope it helps
