### ISSUE TITLE
sources options provide the callback function to match?

### ISSUE THREAD

**Issue by icai** [website-scraper/node-website-scraper#380]
### Configuration
**version:** lastest

**options:**  no, i see the source code.
```js



```

### Description

sources options provide the callback function to match?

**Expected behavior:** I want to match something special, If provide the `callback` to use `RegExp` to match children source that may be better.
**Actual behavior:** 

sources: [
{ selector: 'img', attr: 'src' },
{ selector: 'link[rel="stylesheet"]', attr: 'href' },
{ callback:()=>{ return theurl } } // actually what i want
]

### Additional Information

no

**Comment by s0ph1e** [comment]
Hey @icai 

Thank you for suggestion

This module uses cheerio to select html elements so `selector` can be any any selector that cheerio module supports - here is docs for it https://github.com/cheeriojs/cheerio#selectors, maybe you can find a solution with some advances selectors 

At this moment I can not add function for selecting html-elements because cheerio does not support it and website-scraper does not work with html-elements tree directly

Please let me know if your task can be solved with some advanced cheerio selectors

**Comment by icai** [comment]
@s0ph1e Oh, thanks. 
but these not i wanted.  I try to crawl some custom syntax template file. so not just xml syntax file.

**Comment by icai** [comment]
I write a simple tool to do this.  https://github.com/icai/esc-crawl

**Comment by s0ph1e** [comment]
Probably website-scraper is not suitable for your task since it works with html and css files.
Glad that you found a solution 👍
