### ISSUE TITLE
Relative child URLs not updated consistently 

### ISSUE THREAD

**Issue by tverona1** [website-scraper/node-website-scraper#419]
Depending on max recursive depth and traversal order, relative child URLs may not be correctly updated.

For example, take a 3-page site with the following references:
pageA -> pageB
pageA -> pageC
pageB -> pageC

With max recursive depth of 1, all 3 pages should be reachable and entire site should be downloaded correctly. However, when traversing pageA->pageB, reference from pageB->pageC is not processed because max recursive depth is reached. So pageB has a dangling reference, even though pageC is downloaded.

Would it be possible to compute the relative path to pageC, even if pageC ends up being downloaded later, to address this issue?

**Comment by s0ph1e** [comment]
Hi @tverona1 👋 

Thank you for sharing it

Really reference from PageB->Pagec is not updated because of max depth. 
I've created test which demonstrates this behavior in #422. It would be nice to update such resources which were already downloaded. 

I'll not have time to work on it in nearest future, feel free to contribute :) 

As for quick solution - I suggest to take a look on [getReference](https://github.com/website-scraper/node-website-scraper#getreference) action, maybe it can help to work around this problem
