### ISSUE TITLE
Pass options to Cheerio?

### ISSUE THREAD

**Issue by gmhenderson** [website-scraper/node-website-scraper#484]
I recently had the need to set a specific option for Cheerio (`scriptingEnabled: false`) but there is currently no way to pass any configuration options. Does it make sense to create a config option that can be passed along to Cheerio?

**Comment by s0ph1e** [comment]
Hi @gmhenderson 👋 

Sorry for late response.

Could you please share a use-case example when it can be needed? 
I didn't face such need before and I'm not sure about config option for cheerio because making cheerio more configurable will make it easier to break everything (website-scraper will not work as expected without current options for cheerio)

**Comment by s0ph1e** [comment]
Thanks for sharing @gmhenderson 👍 

Yep, makes sense to have content inside `<noscript>` parsed. I'll leave the issue open and think about proper solution. 
Maybe it makes sense to have always `{ scriptingEnabled: false }` 🤔

**Comment by gmhenderson** [comment]
I think always using `{ scriptingEnabled: false }` makes sense since Javascript is not being parsed, but it seems like that could possibly break some existing projects.
